### ISSUE TITLE
Error when Running local-bo.py - FileNotFoundError in Demo

### ISSUE THREAD

**Issue by tspp520** [RaulAstudillo06/PSBAX#1]
Hi,

After installing the environment and switching to it, I navigated to the `.../PSBAX/demos` directory and ran the following command:

```
python3 local-bo.py
```

However, I encountered the following error message:

```
Traceback (most recent call last):
  File "/data2/Bio_ai/PSBAX/demos/graph.py", line 68, in <module>
    for f in os.listdir(files_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/data2/Bio_ai/PSBAX/demos/results/local-bo_hartmann_3d/random_1'
```

Could you please help me figure out what went wrong?

Thank you!

**Comment by tspp520** [comment]
I first tried running the script using:
```
python3 local-bo.py
```

but encountered an error. I then tried running it with the command:

```
python local-bo.py
```

This resulted in the following error message:

```
Traceback (most recent call last):
  File "/data2/Bio_ai/PSBAX/demos/graph.py", line 68, in <module>
    for f in os.listdir(files_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/data2/Bio_ai/PSBAX/demos/results/local-bo_hartmann_3d/random_1'
```

Could you please clarify the correct command to use and whether the missing directory should be created manually or if it's generated by the script?

Thanks for your help!
